name: CI/CD Pipeline

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
	with: 
		fetch-depth: 0

      - name: List Files (Debugging)
        run: ls -l
	
      - name: Finish Deployment
      - run: echo "Deployment Successful."
